# Este workflow é pra instalar as dependências do Python,
# rodar os testes e o linter com uma única versão do Python.
# Para mais informações, veja:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi

    - name: Lint com flake8
      run: |


    - name: Testar com pytest
      run: |
        pytest
